// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmccum6c83OmtgOsHCfBcDIX3zgFK3xKo',
    appId: '1:59243708382:android:3e014623deca31de7ce74f',
    messagingSenderId: '59243708382',
    projectId: 'nephrogo-f06fe',
    storageBucket: 'nephrogo-f06fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyiX6VgxJ8FtQ-rCJtS7blaLjWyAbHZUM',
    appId: '1:59243708382:ios:118cbcbc535335b57ce74f',
    messagingSenderId: '59243708382',
    projectId: 'nephrogo-f06fe',
    storageBucket: 'nephrogo-f06fe.appspot.com',
    androidClientId:
        '59243708382-67s7i406v1rrv3orh5u8tqvu6thclqc7.apps.googleusercontent.com',
    iosClientId:
        '59243708382-i7vp7hs924nq5oc44pjtr95ioa2391on.apps.googleusercontent.com',
    iosBundleId: 'com.nephrogo',
  );
}
