# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to Firebase Beta"
  lane :beta do
    # get_certificates           # invokes cert
    # get_provisioning_profile   # invokes sigh
    setup_ci(provider: "travis")
    sync_code_signing(type: "appstore", app_identifier: "com.nephrogo", git_url: "https://github.com/vycius/apple-ios-certficates.git", readonly: true)
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    firebase_app_distribution(
        app: "1:59243708382:ios:118cbcbc535335b57ce74f",
        groups: "internal"
     )
  end

  desc "Push a new release build to the App Store"
  lane :release do
    setup_ci(provider: "travis")
    sync_code_signing(type: "appstore", app_identifier: "com.nephrogo", git_url: "https://github.com/vycius/apple-ios-certficates.git", readonly: true)
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_app_store
  end
end
