name: Build Nephrolog Mobile Application
on: [push, pull_request]

jobs:
  build_android:
    name: Build Nephrolog Android version
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-java@v1
        with:
          java-version: '15.x'

      - run: echo $ANDROID_SIGNING_KEY_BASE64 | base64 -d > android/app/key.jks
        env:
          ANDROID_SIGNING_KEY_BASE64: ${{ secrets.ANDROID_SIGNING_KEY_BASE64 }}

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - run: dart --version
      - run: flutter --version

      - run: flutter pub get

      - run: flutter analyze

      - run: flutter build apk
        env:
          KEY_STORE_PASSWORD: ${{ secrets.ANDROID_SIGNING_KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}
          KEY_PATH: key.jks

      - uses: actions/upload-artifact@v2
        name: Upload Android APK
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - uses: actions/upload-artifact@v2
        name: Upload Proguard mapping.txt
        with:
          name: mapping.txt
          path: build/app/outputs/mapping/release/mapping.txt

      - uses: actions/upload-artifact@v2
        name: Upload pubspec.lock
        with:
          name: pubspec.lock
          path: pubspec.lock