name: Build Nephrolog Mobile Application
on: [push, pull_request]

jobs:
  build_android:
    name: Build Nephrolog Android version
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-java@v1
        with:
          java-version: '15.x'

      - run: echo $ANDROID_SIGNING_KEY_BASE64 | base64 -d > android/app/key.jks
        env:
          ANDROID_SIGNING_KEY_BASE64: ${{ secrets.ANDROID_SIGNING_KEY_BASE64 }}

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - run: dart --version
      - run: flutter --version

      - run: flutter pub get

      - run: flutter analyze || true

      - run: flutter test

      - run: flutter build appbundle --build-number $(git rev-list --count HEAD)
        env:
          KEY_STORE_PASSWORD: ${{ secrets.ANDROID_SIGNING_KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}
          KEY_PATH: key.jks

      - uses: actions/upload-artifact@v2
        name: Upload Android AAB
        with:
          name: app-release.aab
          path: build/app/outputs/bundle/release/app-release.aab

      - uses: actions/upload-artifact@v2
        name: Upload Proguard mapping.txt
        with:
          name: mapping.txt
          path: build/app/outputs/mapping/release/mapping.txt

      - uses: actions/upload-artifact@v2
        name: Upload pubspec.lock
        with:
          name: pubspec.lock
          path: pubspec.lock

      - run: flutter build apk --build-number $(git rev-list --count HEAD)
        env:
          KEY_STORE_PASSWORD: ${{ secrets.ANDROID_SIGNING_KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}
          KEY_PATH: key.jks

      - uses: actions/upload-artifact@v2
        name: Upload Android APK
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build_web:
    name: Build Nephrolog WEB version
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@master

      - uses: subosito/flutter-action@v1
        with:
          channel: beta

      - run: flutter config --enable-web

      - run: dart --version
      - run: flutter --version

      - run: flutter pub get

      - run: flutter build web

  deploy_android_internal_testing:
    name: Deploys Android ABB to Google play for Internal Testing
    runs-on: ubuntu-20.04
    needs: build_android
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@master

      - name: Download APK
        uses: actions/download-artifact@v2
        with:
          name: app-release.apk

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.ANDROID_FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: internal
          file: app-release.apk