name: Build and deploy nephrolog WEB
on: [push, pull_request]

jobs:
  deploy_web:
    name: Build and deploy Nephrolog WEB
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@master

      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - run: dart --version
      - run: flutter --version

      - run: flutter pub get

#      - run: flutter analyze

      - name: Build WEB
        run: flutter build web --release

      - name: Deploy WEB 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/web
          CLEAN: true

      - uses: actions/upload-artifact@v2
        name: Upload pubspec.lock
        with:
          name: pubspec.lock
          path: pubspec.lock

